<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // multiple row create
        $countries = collect([
            ['name' => 'Afghanistan', 'iso_code_2' => 'AF', 'iso_code_3' => 'AFG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Albania', 'iso_code_2' => 'AL', 'iso_code_3' => 'ALB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Algeria', 'iso_code_2' => 'DZ', 'iso_code_3' => 'DZA', 'postcode' => 0, 'status' => 1],
            ['name' => 'American Samoa', 'iso_code_2' => 'AS', 'iso_code_3' => 'ASM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Andorra', 'iso_code_2' => 'AD', 'iso_code_3' => 'AND', 'postcode' => 0, 'status' => 1],
            ['name' => 'Angola', 'iso_code_2' => 'AO', 'iso_code_3' => 'AGO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Anguilla', 'iso_code_2' => 'AI', 'iso_code_3' => 'AIA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Antarctica', 'iso_code_2' => 'AQ', 'iso_code_3' => 'ATA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Antigua and Barbuda', 'iso_code_2' => 'AG', 'iso_code_3' => 'ATG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Argentina', 'iso_code_2' => 'AR', 'iso_code_3' => 'ARG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Armenia', 'iso_code_2' => 'AM', 'iso_code_3' => 'ARM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Aruba', 'iso_code_2' => 'AW', 'iso_code_3' => 'ABW', 'postcode' => 0, 'status' => 1],
            ['name' => 'Australia', 'iso_code_2' => 'AU', 'iso_code_3' => 'AUS', 'postcode' => 0, 'status' => 1],
            ['name' => 'Austria', 'iso_code_2' => 'AT', 'iso_code_3' => 'AUT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Azerbaijan', 'iso_code_2' => 'AZ', 'iso_code_3' => 'AZE', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bahamas', 'iso_code_2' => 'BS', 'iso_code_3' => 'BHS', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bahrain', 'iso_code_2' => 'BH', 'iso_code_3' => 'BHR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bangladesh', 'iso_code_2' => 'BD', 'iso_code_3' => 'BGD', 'postcode' => 0, 'status' => 1],
            ['name' => 'Barbados', 'iso_code_2' => 'BB', 'iso_code_3' => 'BRB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Belarus', 'iso_code_2' => 'BY', 'iso_code_3' => 'BLR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Belgium', 'iso_code_2' => 'BE', 'iso_code_3' => 'BEL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Belize', 'iso_code_2' => 'BZ', 'iso_code_3' => 'BLZ', 'postcode' => 0, 'status' => 1],
            ['name' => 'Benin', 'iso_code_2' => 'BJ', 'iso_code_3' => 'BEN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bermuda', 'iso_code_2' => 'BM', 'iso_code_3' => 'BMU', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bhutan', 'iso_code_2' => 'BT', 'iso_code_3' => 'BTN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bolivia', 'iso_code_2' => 'BO', 'iso_code_3' => 'BOL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bosnia and Herzegowina', 'iso_code_2' => 'BA', 'iso_code_3' => 'BIH', 'postcode' => 0, 'status' => 1],
            ['name' => 'Botswana', 'iso_code_2' => 'BW', 'iso_code_3' => 'BWA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bouvet Island', 'iso_code_2' => 'BV', 'iso_code_3' => 'BVT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Brazil', 'iso_code_2' => 'BR', 'iso_code_3' => 'BRA', 'postcode' => 0, 'status' => 1],
            ['name' => 'British Indian Ocean Territory', 'iso_code_2' => 'IO', 'iso_code_3' => 'IOT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Brunei Darussalam', 'iso_code_2' => 'BN', 'iso_code_3' => 'BRN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Bulgaria', 'iso_code_2' => 'BG', 'iso_code_3' => 'BGR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Burkina Faso', 'iso_code_2' => 'BF', 'iso_code_3' => 'BFA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Burundi', 'iso_code_2' => 'BI', 'iso_code_3' => 'BDI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Cambodia', 'iso_code_2' => 'KH', 'iso_code_3' => 'KHM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Cameroon', 'iso_code_2' => 'CM', 'iso_code_3' => 'CMR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Canada', 'iso_code_2' => 'CA', 'iso_code_3' => 'CAN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Cape Verde', 'iso_code_2' => 'CV', 'iso_code_3' => 'CPV', 'postcode' => 0, 'status' => 1],
            ['name' => 'Cayman Islands', 'iso_code_2' => 'KY', 'iso_code_3' => 'CYM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Central African Republic', 'iso_code_2' => 'CF', 'iso_code_3' => 'CAF', 'postcode' => 0, 'status' => 1],
            ['name' => 'Chad', 'iso_code_2' => 'TD', 'iso_code_3' => 'TCD', 'postcode' => 0, 'status' => 1],
            ['name' => 'Chile', 'iso_code_2' => 'CL', 'iso_code_3' => 'CHL', 'postcode' => 0, 'status' => 1],
            ['name' => 'China', 'iso_code_2' => 'CN', 'iso_code_3' => 'CHN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Christmas Island', 'iso_code_2' => 'CX', 'iso_code_3' => 'CXR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Colombia', 'iso_code_2' => 'CO', 'iso_code_3' => 'COL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Comoros', 'iso_code_2' => 'KM', 'iso_code_3' => 'COM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Congo', 'iso_code_2' => 'CG', 'iso_code_3' => 'COG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Cook Islands', 'iso_code_2' => 'CK', 'iso_code_3' => 'COK', 'postcode' => 0, 'status' => 1],
            ['name' => 'Costa Rica', 'iso_code_2' => 'CR', 'iso_code_3' => 'CRI', 'postcode' => 0, 'status' => 1],
            ['name' => "Cote D'Ivoire", 'iso_code_2' => 'CI', 'iso_code_3' => 'CIV', 'postcode' => 0, 'status' => 1],
            ['name' => 'Croatia', 'iso_code_2' => 'HR', 'iso_code_3' => 'HRV', 'postcode' => 0, 'status' => 1],
            ['name' => 'Cuba', 'iso_code_2' => 'CU', 'iso_code_3' => 'CUB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Cyprus', 'iso_code_2' => 'CY', 'iso_code_3' => 'CYP', 'postcode' => 0, 'status' => 1],
            ['name' => 'Czech Republic', 'iso_code_2' => 'CZ', 'iso_code_3' => 'CZE', 'postcode' => 0, 'status' => 1],
            ['name' => 'Denmark', 'iso_code_2' => 'DK', 'iso_code_3' => 'DNK', 'postcode' => 0, 'status' => 1],
            ['name' => 'Djibouti', 'iso_code_2' => 'DJ', 'iso_code_3' => 'DJI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Dominica', 'iso_code_2' => 'DM', 'iso_code_3' => 'DMA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Dominican Republic', 'iso_code_2' => 'DO', 'iso_code_3' => 'DOM', 'postcode' => 0, 'status' => 1],
            ['name' => 'East Timor', 'iso_code_2' => 'TP', 'iso_code_3' => 'TMP', 'postcode' => 0, 'status' => 1],
            ['name' => 'Ecuador', 'iso_code_2' => 'EC', 'iso_code_3' => 'ECU', 'postcode' => 0, 'status' => 1],
            ['name' => 'Egypt', 'iso_code_2' => 'EG', 'iso_code_3' => 'EGY', 'postcode' => 0, 'status' => 1],
            ['name' => 'El Salvador', 'iso_code_2' => 'SV', 'iso_code_3' => 'SLV', 'postcode' => 0, 'status' => 1],
            ['name' => 'Equatorial Guinea', 'iso_code_2' => 'GQ', 'iso_code_3' => 'GNQ', 'postcode' => 0, 'status' => 1],
            ['name' => 'Eritrea', 'iso_code_2' => 'ER', 'iso_code_3' => 'ERI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Estonia', 'iso_code_2' => 'EE', 'iso_code_3' => 'EST', 'postcode' => 0, 'status' => 1],
            ['name' => 'Ethiopia', 'iso_code_2' => 'ET', 'iso_code_3' => 'ETH', 'postcode' => 0, 'status' => 1],
            ['name' => 'Falkland Islands (Malvinas)', 'iso_code_2' => 'FK', 'iso_code_3' => 'FLK', 'postcode' => 0, 'status' => 1],
            ['name' => 'Faroe Islands', 'iso_code_2' => 'FO', 'iso_code_3' => 'FRO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Fiji', 'iso_code_2' => 'FJ', 'iso_code_3' => 'FJI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Finland', 'iso_code_2' => 'FI', 'iso_code_3' => 'FIN', 'postcode' => 0, 'status' => 1],
            ['name' => 'France', 'iso_code_2' => 'FR', 'iso_code_3' => 'FRA', 'postcode' => 0, 'status' => 1],
            ['name' => 'France, Metropolitan', 'iso_code_2' => 'FX', 'iso_code_3' => 'FXX', 'postcode' => 0, 'status' => 1],
            ['name' => 'French Guiana', 'iso_code_2' => 'GF', 'iso_code_3' => 'GUF', 'postcode' => 0, 'status' => 1],
            ['name' => 'French Polynesia', 'iso_code_2' => 'PF', 'iso_code_3' => 'PYF', 'postcode' => 0, 'status' => 1],
            ['name' => 'French Southern Territories', 'iso_code_2' => 'TF', 'iso_code_3' => 'ATF', 'postcode' => 0, 'status' => 1],
            ['name' => 'Gabon', 'iso_code_2' => 'GA', 'iso_code_3' => 'GAB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Gambia', 'iso_code_2' => 'GM', 'iso_code_3' => 'GMB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Georgia', 'iso_code_2' => 'GE', 'iso_code_3' => 'GEO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Germany', 'iso_code_2' => 'DE', 'iso_code_3' => 'DEU', 'address_format' => "{company}\r\n{firstname} {lastname}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}", 'postcode' => 1, 'status' => 1],
            ['name' => 'Ghana', 'iso_code_2' => 'GH', 'iso_code_3' => 'GHA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Global', 'iso_code_2' => 'GI', 'iso_code_3' => 'GIB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Greece', 'iso_code_2' => 'GR', 'iso_code_3' => 'GRC', 'postcode' => 0, 'status' => 1],
            ['name' => 'Greenland', 'iso_code_2' => 'GL', 'iso_code_3' => 'GRL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Grenada', 'iso_code_2' => 'GD', 'iso_code_3' => 'GRD', 'postcode' => 0, 'status' => 1],
            ['name' => 'Guadeloupe', 'iso_code_2' => 'GP', 'iso_code_3' => 'GLP', 'postcode' => 0, 'status' => 1],
            ['name' => 'Guam', 'iso_code_2' => 'GU', 'iso_code_3' => 'GUM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Guatemala', 'iso_code_2' => 'GT', 'iso_code_3' => 'GTM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Guinea', 'iso_code_2' => 'GN', 'iso_code_3' => 'GIN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Guinea-bissau', 'iso_code_2' => 'GW', 'iso_code_3' => 'GNB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Guyana', 'iso_code_2' => 'GY', 'iso_code_3' => 'GUY', 'postcode' => 0, 'status' => 1],
            ['name' => 'Haiti', 'iso_code_2' => 'HT', 'iso_code_3' => 'HTI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Heard and Mc Donald Islands', 'iso_code_2' => 'HM', 'iso_code_3' => 'HMD', 'postcode' => 0, 'status' => 1],
            ['name' => 'Honduras', 'iso_code_2' => 'HN', 'iso_code_3' => 'HND', 'postcode' => 0, 'status' => 1],
            ['name' => 'Hong Kong', 'iso_code_2' => 'HK', 'iso_code_3' => 'HKG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Hungary', 'iso_code_2' => 'HU', 'iso_code_3' => 'HUN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Iceland', 'iso_code_2' => 'IS', 'iso_code_3' => 'ISL', 'postcode' => 0, 'status' => 1],
            ['name' => 'India', 'iso_code_2' => 'IN', 'iso_code_3' => 'IND', 'postcode' => 0, 'status' => 1],
            ['name' => 'Indonesia', 'iso_code_2' => 'ID', 'iso_code_3' => 'IDN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Iran (Islamic Republic of)', 'iso_code_2' => 'IR', 'iso_code_3' => 'IRN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Iraq', 'iso_code_2' => 'IQ', 'iso_code_3' => 'IRQ', 'postcode' => 0, 'status' => 1],
            ['name' => 'Ireland', 'iso_code_2' => 'IE', 'iso_code_3' => 'IRL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Israel', 'iso_code_2' => 'IL', 'iso_code_3' => 'ISR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Italy', 'iso_code_2' => 'IT', 'iso_code_3' => 'ITA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Jamaica', 'iso_code_2' => 'JM', 'iso_code_3' => 'JAM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Japan', 'iso_code_2' => 'JP', 'iso_code_3' => 'JPN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Jordan', 'iso_code_2' => 'JO', 'iso_code_3' => 'JOR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Kazakhstan', 'iso_code_2' => 'KZ', 'iso_code_3' => 'KAZ', 'postcode' => 0, 'status' => 1],
            ['name' => 'Kenya', 'iso_code_2' => 'KE', 'iso_code_3' => 'KEN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Kiribati', 'iso_code_2' => 'KI', 'iso_code_3' => 'KIR', 'postcode' => 0, 'status' => 1],
            ['name' => 'North Korea', 'iso_code_2' => 'KP', 'iso_code_3' => 'PRK', 'postcode' => 0, 'status' => 1],
            ['name' => 'Korea, Republic of', 'iso_code_2' => 'KR', 'iso_code_3' => 'KOR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Kuwait', 'iso_code_2' => 'KW', 'iso_code_3' => 'KWT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Kyrgyzstan', 'iso_code_2' => 'KG', 'iso_code_3' => 'KGZ', 'postcode' => 0, 'status' => 1],
            ['name' => "Lao People's Democratic Republic", 'iso_code_2' => 'LA', 'iso_code_3' => 'LAO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Latvia', 'iso_code_2' => 'LV', 'iso_code_3' => 'LVA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Lebanon', 'iso_code_2' => 'LB', 'iso_code_3' => 'LBN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Lesotho', 'iso_code_2' => 'LS', 'iso_code_3' => 'LSO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Liberia', 'iso_code_2' => 'LR', 'iso_code_3' => 'LBR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Libyan Arab Jamahiriya', 'iso_code_2' => 'LY', 'iso_code_3' => 'LBY', 'postcode' => 0, 'status' => 1],
            ['name' => 'Liechtenstein', 'iso_code_2' => 'LI', 'iso_code_3' => 'LIE', 'postcode' => 0, 'status' => 1],
            ['name' => 'Lithuania', 'iso_code_2' => 'LT', 'iso_code_3' => 'LTU', 'postcode' => 0, 'status' => 1],
            ['name' => 'Luxembourg', 'iso_code_2' => 'LU', 'iso_code_3' => 'LUX', 'postcode' => 0, 'status' => 1],
            ['name' => 'Macau', 'iso_code_2' => 'MO', 'iso_code_3' => 'MAC', 'postcode' => 0, 'status' => 1],
            ['name' => 'FYROM', 'iso_code_2' => 'MK', 'iso_code_3' => 'MKD', 'postcode' => 0, 'status' => 1],
            ['name' => 'Madagascar', 'iso_code_2' => 'MG', 'iso_code_3' => 'MDG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Malawi', 'iso_code_2' => 'MW', 'iso_code_3' => 'MWI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Malaysia', 'iso_code_2' => 'MY', 'iso_code_3' => 'MYS', 'postcode' => 0, 'status' => 1],
            ['name' => 'Maldives', 'iso_code_2' => 'MV', 'iso_code_3' => 'MDV', 'postcode' => 0, 'status' => 1],
            ['name' => 'Mali', 'iso_code_2' => 'ML', 'iso_code_3' => 'MLI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Malta', 'iso_code_2' => 'MT', 'iso_code_3' => 'MLT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Marshall Islands', 'iso_code_2' => 'MH', 'iso_code_3' => 'MHL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Martinique', 'iso_code_2' => 'MQ', 'iso_code_3' => 'MTQ', 'postcode' => 0, 'status' => 1],
            ['name' => 'Mauritania', 'iso_code_2' => 'MR', 'iso_code_3' => 'MRT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Mauritius', 'iso_code_2' => 'MU', 'iso_code_3' => 'MUS', 'postcode' => 0, 'status' => 1],
            ['name' => 'Mayotte', 'iso_code_2' => 'YT', 'iso_code_3' => 'MYT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Mexico', 'iso_code_2' => 'MX', 'iso_code_3' => 'MEX', 'postcode' => 0, 'status' => 1],
            ['name' => 'Micronesia, Federated States of', 'iso_code_2' => 'FM', 'iso_code_3' => 'FSM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Moldova, Republic of', 'iso_code_2' => 'MD', 'iso_code_3' => 'MDA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Monaco', 'iso_code_2' => 'MC', 'iso_code_3' => 'MCO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Mongolia', 'iso_code_2' => 'MN', 'iso_code_3' => 'MNG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Montserrat', 'iso_code_2' => 'MS', 'iso_code_3' => 'MSR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Morocco', 'iso_code_2' => 'MA', 'iso_code_3' => 'MAR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Mozambique', 'iso_code_2' => 'MZ', 'iso_code_3' => 'MOZ', 'postcode' => 0, 'status' => 1],
            ['name' => 'Myanmar', 'iso_code_2' => 'MM', 'iso_code_3' => 'MMR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Namibia', 'iso_code_2' => 'NA', 'iso_code_3' => 'NAM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Nauru', 'iso_code_2' => 'NR', 'iso_code_3' => 'NRU', 'postcode' => 0, 'status' => 1],
            ['name' => 'Nepal', 'iso_code_2' => 'NP', 'iso_code_3' => 'NPL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Netherlands', 'iso_code_2' => 'NL', 'iso_code_3' => 'NLD', 'postcode' => 0, 'status' => 1],
            ['name' => 'Netherlands Antilles', 'iso_code_2' => 'AN', 'iso_code_3' => 'ANT', 'postcode' => 0, 'status' => 1],
            ['name' => 'New Caledonia', 'iso_code_2' => 'NC', 'iso_code_3' => 'NCL', 'postcode' => 0, 'status' => 1],
            ['name' => 'New Zealand', 'iso_code_2' => 'NZ', 'iso_code_3' => 'NZL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Nicaragua', 'iso_code_2' => 'NI', 'iso_code_3' => 'NIC', 'postcode' => 0, 'status' => 1],
            ['name' => 'Niger', 'iso_code_2' => 'NE', 'iso_code_3' => 'NER', 'postcode' => 0, 'status' => 1],
            ['name' => 'Nigeria', 'iso_code_2' => 'NG', 'iso_code_3' => 'NGA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Niue', 'iso_code_2' => 'NU', 'iso_code_3' => 'NIU', 'postcode' => 0, 'status' => 1],
            ['name' => 'Norfolk Island', 'iso_code_2' => 'NF', 'iso_code_3' => 'NFK', 'postcode' => 0, 'status' => 1],
            ['name' => 'Northern Mariana Islands', 'iso_code_2' => 'MP', 'iso_code_3' => 'MNP', 'postcode' => 0, 'status' => 1],
            ['name' => 'Norway', 'iso_code_2' => 'NO', 'iso_code_3' => 'NOR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Oman', 'iso_code_2' => 'OM', 'iso_code_3' => 'OMN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Pakistan', 'iso_code_2' => 'PK', 'iso_code_3' => 'PAK', 'postcode' => 0, 'status' => 1],
            ['name' => 'Palau', 'iso_code_2' => 'PW', 'iso_code_3' => 'PLW', 'postcode' => 0, 'status' => 1],
            ['name' => 'Panama', 'iso_code_2' => 'PA', 'iso_code_3' => 'PAN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Papua New Guinea', 'iso_code_2' => 'PG', 'iso_code_3' => 'PNG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Paraguay', 'iso_code_2' => 'PY', 'iso_code_3' => 'PRY', 'postcode' => 0, 'status' => 1],
            ['name' => 'Peru', 'iso_code_2' => 'PE', 'iso_code_3' => 'PER', 'postcode' => 0, 'status' => 1],
            ['name' => 'Philippines', 'iso_code_2' => 'PH', 'iso_code_3' => 'PHL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Pitcairn', 'iso_code_2' => 'PN', 'iso_code_3' => 'PCN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Poland', 'iso_code_2' => 'PL', 'iso_code_3' => 'POL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Portugal', 'iso_code_2' => 'PT', 'iso_code_3' => 'PRT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Puerto Rico', 'iso_code_2' => 'PR', 'iso_code_3' => 'PRI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Qatar', 'iso_code_2' => 'QA', 'iso_code_3' => 'QAT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Reunion', 'iso_code_2' => 'RE', 'iso_code_3' => 'REU', 'postcode' => 0, 'status' => 1],
            ['name' => 'Romania', 'iso_code_2' => 'RO', 'iso_code_3' => 'ROM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Russian Federation', 'iso_code_2' => 'RU', 'iso_code_3' => 'RUS', 'postcode' => 0, 'status' => 1],
            ['name' => 'Rwanda', 'iso_code_2' => 'RW', 'iso_code_3' => 'RWA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Saint Kitts and Nevis', 'iso_code_2' => 'KN', 'iso_code_3' => 'KNA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Saint Lucia', 'iso_code_2' => 'LC', 'iso_code_3' => 'LCA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code_2' => 'VC', 'iso_code_3' => 'VCT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Samoa', 'iso_code_2' => 'WS', 'iso_code_3' => 'WSM', 'postcode' => 0, 'status' => 1],
            ['name' => 'San Marino', 'iso_code_2' => 'SM', 'iso_code_3' => 'SMR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Sao Tome and Principe', 'iso_code_2' => 'ST', 'iso_code_3' => 'STP', 'postcode' => 0, 'status' => 1],
            ['name' => 'Saudi Arabia', 'iso_code_2' => 'SA', 'iso_code_3' => 'SAU', 'postcode' => 0, 'status' => 1],
            ['name' => 'Senegal', 'iso_code_2' => 'SN', 'iso_code_3' => 'SEN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Seychelles', 'iso_code_2' => 'SC', 'iso_code_3' => 'SYC', 'postcode' => 0, 'status' => 1],
            ['name' => 'Sierra Leone', 'iso_code_2' => 'SL', 'iso_code_3' => 'SLE', 'postcode' => 0, 'status' => 1],
            ['name' => 'Singapore', 'iso_code_2' => 'SG', 'iso_code_3' => 'SGP', 'postcode' => 0, 'status' => 1],
            ['name' => 'Slovak Republic', 'iso_code_2' => 'SK', 'iso_code_3' => 'SVK', 'address_format' => "{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city} {postcode}\r\n{zone}\r\n{country}", 'postcode' => 0, 'status' => 1],
            ['name' => 'Slovenia', 'iso_code_2' => 'SI', 'iso_code_3' => 'SVN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Solomon Islands', 'iso_code_2' => 'SB', 'iso_code_3' => 'SLB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Somalia', 'iso_code_2' => 'SO', 'iso_code_3' => 'SOM', 'postcode' => 0, 'status' => 1],
            ['name' => 'South Africa', 'iso_code_2' => 'ZA', 'iso_code_3' => 'ZAF', 'postcode' => 0, 'status' => 1],
            ['name' => 'South Georgia & South Sandwich Islands', 'iso_code_2' => 'GS', 'iso_code_3' => 'SGS', 'postcode' => 0, 'status' => 1],
            ['name' => 'Spain', 'iso_code_2' => 'ES', 'iso_code_3' => 'ESP', 'postcode' => 0, 'status' => 1],
            ['name' => 'Sri Lanka', 'iso_code_2' => 'LK', 'iso_code_3' => 'LKA', 'postcode' => 0, 'status' => 1],
            ['name' => 'St. Helena', 'iso_code_2' => 'SH', 'iso_code_3' => 'SHN', 'postcode' => 0, 'status' => 1],
            ['name' => 'St. Pierre and Miquelon', 'iso_code_2' => 'PM', 'iso_code_3' => 'SPM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Sudan', 'iso_code_2' => 'SD', 'iso_code_3' => 'SDN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Suriname', 'iso_code_2' => 'SR', 'iso_code_3' => 'SUR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Svalbard and Jan Mayen Islands', 'iso_code_2' => 'SJ', 'iso_code_3' => 'SJM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Swaziland', 'iso_code_2' => 'SZ', 'iso_code_3' => 'SWZ', 'postcode' => 0, 'status' => 1],
            ['name' => 'Sweden', 'iso_code_2' => 'SE', 'iso_code_3' => 'SWE', 'postcode' => 0, 'status' => 1],
            ['name' => 'Switzerland', 'iso_code_2' => 'CH', 'iso_code_3' => 'CHE', 'postcode' => 0, 'status' => 1],
            ['name' => 'Syrian Arab Republic', 'iso_code_2' => 'SY', 'iso_code_3' => 'SYR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Taiwan', 'iso_code_2' => 'TW', 'iso_code_3' => 'TWN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Tajikistan', 'iso_code_2' => 'TJ', 'iso_code_3' => 'TJK', 'postcode' => 0, 'status' => 1],
            ['name' => 'Tanzania, United Republic of', 'iso_code_2' => 'TZ', 'iso_code_3' => 'TZA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Thailand', 'iso_code_2' => 'TH', 'iso_code_3' => 'THA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Togo', 'iso_code_2' => 'TG', 'iso_code_3' => 'TGO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Tokelau', 'iso_code_2' => 'TK', 'iso_code_3' => 'TKL', 'postcode' => 0, 'status' => 1],
            ['name' => 'Tonga', 'iso_code_2' => 'TO', 'iso_code_3' => 'TON', 'postcode' => 0, 'status' => 1],
            ['name' => 'Trinidad and Tobago', 'iso_code_2' => 'TT', 'iso_code_3' => 'TTO', 'postcode' => 0, 'status' => 1],
            ['name' => 'Tunisia', 'iso_code_2' => 'TN', 'iso_code_3' => 'TUN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Turkey', 'iso_code_2' => 'TR', 'iso_code_3' => 'TUR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Turkmenistan', 'iso_code_2' => 'TM', 'iso_code_3' => 'TKM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Turks and Caicos Islands', 'iso_code_2' => 'TC', 'iso_code_3' => 'TCA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Tuvalu', 'iso_code_2' => 'TV', 'iso_code_3' => 'TUV', 'postcode' => 0, 'status' => 1],
            ['name' => 'Uganda', 'iso_code_2' => 'UG', 'iso_code_3' => 'UGA', 'postcode' => 0, 'status' => 1],
            ['name' => 'Ukraine', 'iso_code_2' => 'UA', 'iso_code_3' => 'UKR', 'postcode' => 0, 'status' => 1],
            ['name' => 'United Arab Emirates', 'iso_code_2' => 'AE', 'iso_code_3' => 'ARE', 'postcode' => 0, 'status' => 1],
            ['name' => 'United Kingdom', 'iso_code_2' => 'GB', 'iso_code_3' => 'GBR', 'postcode' => 1, 'status' => 1],
            ['name' => 'United States', 'iso_code_2' => 'US', 'iso_code_3' => 'USA', 'address_format' => "{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city}, {zone} {postcode}\r\n{country}", 'postcode' => 0, 'status' => 1],
            ['name' => 'United States Minor Outlying Islands', 'iso_code_2' => 'UM', 'iso_code_3' => 'UMI', 'postcode' => 0, 'status' => 1],
            ['name' => 'Uruguay', 'iso_code_2' => 'UY', 'iso_code_3' => 'URY', 'postcode' => 0, 'status' => 1],
            ['name' => 'Uzbekistan', 'iso_code_2' => 'UZ', 'iso_code_3' => 'UZB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Vanuatu', 'iso_code_2' => 'VU', 'iso_code_3' => 'VUT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Vatican City State (Holy See)', 'iso_code_2' => 'VA', 'iso_code_3' => 'VAT', 'postcode' => 0, 'status' => 1],
            ['name' => 'Venezuela', 'iso_code_2' => 'VE', 'iso_code_3' => 'VEN', 'postcode' => 0, 'status' => 1],
            ['name' => 'Viet Nam', 'iso_code_2' => 'VN', 'iso_code_3' => 'VNM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Virgin Islands (British)', 'iso_code_2' => 'VG', 'iso_code_3' => 'VGB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Virgin Islands (U.S.)', 'iso_code_2' => 'VI', 'iso_code_3' => 'VIR', 'postcode' => 0, 'status' => 1],
            ['name' => 'Wallis and Futuna Islands', 'iso_code_2' => 'WF', 'iso_code_3' => 'WLF', 'postcode' => 0, 'status' => 1],
            ['name' => 'Western Sahara', 'iso_code_2' => 'EH', 'iso_code_3' => 'ESH', 'postcode' => 0, 'status' => 1],
            ['name' => 'Yemen', 'iso_code_2' => 'YE', 'iso_code_3' => 'YEM', 'postcode' => 0, 'status' => 1],
            ['name' => 'Yugoslavia', 'iso_code_2' => 'YU', 'iso_code_3' => 'YUG', 'postcode' => 0, 'status' => 1],
            ['name' => 'Democratic Republic of Congo', 'iso_code_2' => 'CD', 'iso_code_3' => 'COD', 'postcode' => 0, 'status' => 1],
            ['name' => 'Zambia', 'iso_code_2' => 'ZM', 'iso_code_3' => 'ZMB', 'postcode' => 0, 'status' => 1],
            ['name' => 'Zimbabwe', 'iso_code_2' => 'ZW', 'iso_code_3' => 'ZWE', 'postcode' => 0, 'status' => 1],
        ]);

        // Multiple data seeding
        $countries->map(fn($item) => Country::create($item));
    }
}